In [ ]:
import numpy as np

In [ ]:
lst = [[11,12,3],[4,5,6],[7,8,9]]

In [ ]:
lst


[[11, 12, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
lst = np.array(lst)

In [ ]:
lst

array([[11, 12,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
lst.shape

(3, 3)

In [ ]:
lst.max()

12

In [ ]:
lst.argmax()

1

In [ ]:
lst.min()

3

In [ ]:
lst.argmin()

2

In [ ]:
lst2 = [1,2,3,4,5,6]

In [ ]:
lst2 = np.array(lst2)

In [ ]:
lst2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3
          ))

array([0., 0., 0.])

In [ ]:
np.ones(1)

array([1.])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(4)

array([0.16926634, 0.1778944 , 0.25238005, 0.21375243])

In [ ]:
np.random.randint(100)

25

In [ ]:
np.random.randn()

2.6309462757164948

In [ ]:
lst >=11

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])